#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#############################################################################
#           __________                                                      #
#    __  __/ ____/ __ \__ __   This file is part of MicroGP v4!2.0          #
#   / / / / / __/ /_/ / // /   A versatile evolutionary optimizer & fuzzer  #
#  / /_/ / /_/ / ____/ // /_   https://github.com/microgp/microgp4          #
#  \__  /\____/_/   /__  __/                                                #
#    /_/ --MicroGP4-- /_/      You don't need a big goal, be μ-ambitious!   #
#                                                                           #
#############################################################################
# Copyright 2022-23 Giovanni Squillero and Alberto Tonda
# SPDX-License-Identifier: Apache-2.0

import pytest
from datetime import datetime, timedelta
import sys
import platform
import psutil
import networkx as nx
from datetime import datetime
from microgp4.global_symbols import __version__ as version

from microgp4.classes.readymade_macros import *
from microgp4.classes.value_bag import ValueBag


class MutableValueBag(ValueBag):

    def __setitem__(self, key, value):
        self.__dict__[key] = value


def test_macro_zero():
    mz = MacroZero()
    assert isinstance(mz, MacroZero)
    assert hasattr(mz, 'TEXT')
    assert hasattr(mz, 'EXTRA_PARAMETERS')
    assert hasattr(mz, '_parameter_types')
    assert mz.TEXT.startswith('{_comment} Automagically generated by MicroGP')
    assert mz.EXTRA_PARAMETERS == dict()
    assert mz._parameter_types == dict()


def test_info():
    info = Info()
    assert isinstance(info, Info)
    assert hasattr(info, 'TEXT')
    assert hasattr(info, 'EXTRA_PARAMETERS')
    assert hasattr(info, '_parameter_types')
    assert info.TEXT.startswith('{_comment} [INFO] NOW: ')
    assert info.EXTRA_PARAMETERS == dict()
    assert info._parameter_types == dict()


def test_macro_zero_creation():
    mz = MacroZero()
    assert isinstance(mz, MacroZero)


def test_info_creation():
    info = Info()
    assert isinstance(info, Info)


def test_macro_equality():
    mz1 = MacroZero()
    mz2 = MacroZero()
    assert mz1 == mz2

    info1 = Info()
    info2 = Info()
    assert info1 == info2

    assert mz1 != info1
