# Automagically generated by MicroGP v4!2.0a0.dev1 on 15-May-2023 at 16:21:04

.globl _one_max ## -- Begin function one_max
_one_max:
push %rbx
push %rcx
push %rdx
pushq %rbp
movq %rsp, %rbp
movq $0x72374c347ee15000, %rax
movq $0x72374c347ee15000, %rbx
movq $0x72374c347ee15000, %rcx
movq $0x72374c347ee15000, %rdx
addq $0, %rax

jz n7
andq $0x4d2f, %rcx
subq %rcx, %rbx
n7:
xorq %rax, %rbx
addq %rbx, %rdx
jnz n19
jnz n17
jnz n14
andq $0xf81b, %rdx
jnz n18
n14:
subq %rbx, %rcx
jnz n16
n16:
addq $0xe710, %rax
n17:
jnz n19
n18:
andq %rcx, %rbx
n19:
orq $0x9447, %rax

popq %rbp
pop %rdx
pop %rcx
pop %rbx
retq

